/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package piano;

import org.junit.Test;
import static org.junit.Assert.*;

public class BlockTest {
    
    @Test
    public void blockTest() {
        // Block b = new Block();
        // assertFalse(b.isActive());
        // b.click();
        // assertTrue(b.isActive());
        // b.click();
        // assertFalse(b.isActive());
    }
    
}
